### ISSUE TITLE
How about the performance on the other datasets?

### ISSUE THREAD

**Issue by ghost** [gram-ood/zeroshot-ood#1]
May I ask for the performance of the OOD detection on the other datasets using proposed method, in both Resnet and DenseNet? For example,

- CIFAR-100 vs LSUN (cropped)

- CIFAR-100 vs TinyImageNet (cropped)

- CIFAR-100 vs MNIST.

**Comment by zeroshot-ood** [comment]
Additional results for the gram-matrix method and the other baseline methods are reported in the updated repository: https://github.com/vectorinstitute/gram-ood-detection
